version: 2
jobs:
  setup:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - run: |
             curl -fL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
             chmod +x /usr/local/bin/dep
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          key: v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

workflows:
  version: 2
  build_gcs_helper:
    jobs:

