version: 2
jobs:
  setup:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - run: |
             curl -fL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
             chmod +x /usr/local/bin/dep
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          key: v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
  build:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: |
                BUILD_TIME=`date +%FT%T%z`
                APP_PATH=go.athera.io/olympus
                APP_VENDOR_PATH=$APP_PATH/vendor
                APP_BUILD_TAGS="-X $APP_ID -X $APP_PSEUDO_SECRET"
                CGO_ENABLED=0 go build -a -ldflags "${APP_BUILD_TAGS}" ./cmd/gcs-bucket-helper
                echo $APP_ID $APP_PSEUDO_SECRET
                ls -l

workflows:
  version: 2
  build_gcs_helper:
    jobs:
      - setup
      - build:
          requires:
          - setup
