version: 2
jobs:
  setup:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - run: |
             curl -fL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
             chmod +x /usr/local/bin/dep
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          key: v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
  build_linux:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: |

                BUILD_TIME=`date +%FT%T%z`
                APP_PATH=github.com/athera-io/gcs-bucket-helper
                APP_VENDOR_PATH=$APP_PATH/vendor
                APP_BUILD_TAGS="-X main.appID=${APP_ID} -X main.appPseudoSecret=${APP_PSEUDO_SECRET}"
                CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags "${APP_BUILD_TAGS}" ./cmd/gcs-bucket-helper
                mkdir -p ./artifacts/linux
                cp gcs-bucket-helper ./artifacts/linux
      - persist_to_workspace:
          root: .
          paths:
          - ./artifacts/
  build_darwin:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: |
                BUILD_TIME=`date +%FT%T%z`
                APP_PATH=github.com/athera-io/gcs-bucket-helper
                APP_VENDOR_PATH=$APP_PATH/vendor
                APP_BUILD_TAGS="-X main.appID=${APP_ID} -X main.appPseudoSecret=${APP_PSEUDO_SECRET}"
                CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -ldflags "${APP_BUILD_TAGS}" ./cmd/gcs-bucket-helper
                mkdir -p ./artifacts/darwin
                cp gcs-bucket-helper ./artifacts/darwin
      - persist_to_workspace:
          root: .
          paths:
          - ./artifacts/
  build_windows:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-gcs-bucket-helper-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run: |
                BUILD_TIME=`date +%FT%T%z`
                APP_PATH=github.com/athera-io/gcs-bucket-helper
                APP_VENDOR_PATH=$APP_PATH/vendor
                APP_BUILD_TAGS="-X main.appID=${APP_ID} -X main.appPseudoSecret=${APP_PSEUDO_SECRET}"
                CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -ldflags "${APP_BUILD_TAGS}" ./cmd/gcs-bucket-helper
                mkdir -p ./artifacts/windows
                cp gcs-bucket-helper ./artifacts/windows
      - persist_to_workspace:
          root: .
          paths:
          - ./artifacts/
  upload_them_all:
    working_directory: /go/src/github.com/athera-io/gcs-bucket-helper
    docker:
      - image: golang:1.10
    steps:
      - attach_workspace:
          at: .
      - run: ls -lR
workflows:
  version: 2
  build_gcs_helper:
    jobs:
      - setup
      - build_linux:
          requires:
          - setup
      - build_darwin:
          requires:
          - setup
      - build_windows:
          requires:
          - setup
      - upload_them_all:
          requires:
            - build_linux
            - build_darwin
            - build_windows